export const GAME_CONFIG = {
  ARROW_LENGTH: 50,
  ARROW_WIDTH: 8,
  ARROW_SPEED: 14,
  COLLISION_THRESHOLD: 0.18,
  MIN_ARROW_GAP: 0.14,
  CENTER_Y_RATIO: 0.42,
  SHOOT_Y_OFFSET_RATIO: 0.12,
  SHOOT_Y_MIN: 72,
  TARGET_RADIUS_RATIO: 0.12,
  CLEAR_DELAY_MS: 800,
} as const;
